routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\BlogsController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\CommentsController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::get('/',[FrontendController::class,'index'])->name('home');
Route::get('/categories/{category}/blogs',[FrontendController::class,'category'])->name('frontend.category');
Route::get('/tags/{tag}/blogs',[FrontendController::class,'tag'])->name('frontend.tag');
Route::get('/blogs/{blog}',[FrontendController::class,'show'])->name('frontend.blogs.show');
Route::post('/blogs/{blog}/comment',[FrontendController::class,'comment'])->name('frontend.blogs.comment');
Route::delete('/comments/{comment}/delete',[FrontendController::class,'delete'])->name('frontend.comments.delete');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {

    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    Route::prefix('/admin')->name('admin.')->group(function () {
        Route::get('/dashboard', function () {
            return view('admin.dashboard');
        })->name('dashboard');

        Route::get('/blogs/trashed',[BlogsController::class,'trashed'])->name('blogs.trashed');
        Route::get('/blogs/verify',[BlogsController::class,'verify'])->name('blogs.verifyblogs');
        Route::delete('/blogs/{blog}/trash',[BlogsController::class,'trash'])->name('blogs.trash');
        Route::put('/blogs/{blog}/restore',[BlogsController::class,'restore'])->name('blogs.restore');
        Route::post('/blogs/{blog}/verify',[BlogsController::class,'verifyBlog'])->name('blogs.verify');
        Route::post('/blogs/{blog}/unverify',[BlogsController::class,'unverifyBlog'])->name('blogs.unverify');

        Route::get('/blogs/draft',[BlogsController::class,'draft'])->name('blogs.draft');
        Route::post('/blogs/{blog}/restore',[BlogsController::class,'restoreBlog'])->name('blogs.restoreblog');
        Route::post('/blogs/{blog}/drafted',[BlogsController::class,'drafted'])->name('blogs.drafted');
        
        Route::post('/users/{user}/verify',[UsersController::class,'verify'])->name('users.verify');
        Route::post('/users/{user}/unverify',[UsersController::class,'unverify'])->name('users.unverify');
        Route::post('/users/{user}/makeAdmin',[UsersController::class,'makeAdmin'])->name('users.makeAdmin');
        Route::post('/users/{user}/makeAuthor',[UsersController::class,'makeAuthor'])->name('users.makeAuthor');
        
        Route::post('/comments/{comment}/verify',[CommentsController::class,'verify'])->name('comments.verify');
        

        Route::resource('categories', CategoriesController::class)->except(['show']);
        Route::resource('tags', TagsController::class);
        Route::resource('blogs', BlogsController::class);
        Route::resource('users',UsersController::class);  
        Route::resource('comments',CommentsController::class);      
    });
});

require __DIR__.'/auth.php';

app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\Category;
use App\Models\Tag;
use App\Models\Comment;
use Illuminate\Support\Facades\Storage;


class Blog extends Model
{
    use HasFactory, SoftDeletes;

    protected $guarded = [];

    protected $casts = [
        'published_at'=>'datetime'
    ];
    
    public function author()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class)->withTimestamps();
    }

    public function getImagePathAttribute(){
        return '/storage/'.$this->attributes['image_path'];
    }

    public function deleteImage(){
        Storage::delete($this->attributes['image_path']);
        
    }

    public function scopePublished($query){
        return $query->where('published_at','<=',now());
    }
    public function scopeSearch($query){
        $searchParam = request()->search;
        if($searchParam){
            $query = $query->where('title', 'like',"%$searchParam%");
        }
        return $query;
    }

    public function scopeVerified($query){
        return $query->where('blog_status','verified');
    }

    public function comment(){
        return $this->hasMany(Comment::class);
    }
}

app/Http/Controllers/BlogsController.php
<?php

namespace App\Http\Controllers;
use App\Models\Blog;
use App\Models\Category;
use App\Models\Tag;
use Illuminate\Http\Request;
use App\Http\Requests\Blogs\CreateBlogRequest;
use App\Http\Requests\Blogs\UpdateBlogRequest;
use App\Http\Middleware\ValidateAuthor;

class BlogsController extends Controller
{
    public function __construct(){
        $this->middleware(['validateAuthor'])->only(['edit','update','destroy','trash']);
    }
    public function index()
    {
        $authUser = auth()->user();
        if($authUser->isAdmin()){
            $blogs = Blog::with('category')->latest()->paginate(10);
        }else{
            $blogs = Blog::with('category')
                          ->where('user_id',$authUser->id)
                          ->published()
                          ->latest()
                          ->paginate(10);
        }
        
        return view('admin.blogs.index', compact('blogs'));
    }

    public function create(){
        $categories = Category::all();
        $tags = Tag::all();

        return view('admin.blogs.create',compact(['categories','tags']));
    }

    public function store(CreateBlogRequest $request){
        // Image Upload and return the name of the file which will be created
        $image_path = $request->file('image')->store('blogs');
        $data = $request->only(['title','excerpt','body','category_id','published_at']);
        
        $data = array_merge($data, [
            'image_path'=>$image_path,
            'user_id'=>auth()->user()->id
        ]);


        $blog = Blog::create($data);
        // dd($request->tags);
        $blog->tags()->attach($request->tags);

        session()->flash('success','Blog created successfully...');
        return redirect(route('admin.blogs.index'));

    }

    public function edit(Blog $blog){
        $categories = Category::all();
        $tags = Tag::all();

        return view('admin.blogs.edit',compact([
            'categories',
            'tags',
            'blog'
        ]));
    }

    public function update(UpdateBlogRequest $request, Blog $blog) {
        $data = $request->only(['title','excerpt','body','category_id','published_at']);

        if($request->hasFile('image')){
            $image_path = $request->file('image')->store('blogs');
            $blog->deleteImage();
            $data = array_merge($data, ['image_path'=>$image_path]);

        }
        $blog->update($data);
        $blog->tags()->sync($request->tags);

        session()->flash('success','Blog Updated successfully...');
        return redirect(route('admin.blogs.index'));
    }

    public function trash(Blog $blog){
        $blog->delete();

        session()->flash('success','Blog Deleted successfully...');
        return redirect(route('admin.blogs.index'));
    }

    public function destroy(int $blogId){
        $blog = Blog::onlyTrashed()->find($blogId);
        $blog->deleteImage();
        $blog->forceDelete();

        session()->flash('success','Blog Destroyed successfully...');
        return redirect(route('admin.blogs.trashed'));
    }

    public function trashed(){
        $blogs = Blog::with('category')
                ->where('user_id',auth()->id())
                ->onlyTrashed()
                ->latest()
                ->paginate(10);
            
        return view('admin.blogs.trashed', compact('blogs'));
    }

    public function restore(int $blogId){
        $blog = Blog::withTrashed()->find($blogId);
        $blog->restore();

        session()->flash('success','Blog Restored successfully...');
        return redirect(route('admin.blogs.index'));
    }

    public function verify(){
        
        $blogs = Blog::with('category')->latest()->paginate(10);
        return view('admin.blogs.verify',compact(['blogs']));
    }



    public function verifyBlog(Blog $blog){
        $blog->blog_status = "verified";
        $blog->save();
        
        session()->flash('success','Blog Restored successfully...');
        return redirect(route('admin.blogs.verifyblogs'));
       
    }

    public function unverifyBlog(Blog $blog){
        $blog->blog_status = "unverify";
        $blog->save();
        session()->flash('success','Blog Removed from Frontend panel...');
        return redirect(route('admin.blogs.verifyblogs'));

    }

    public function draft(){
        $blogs = Blog::with('category')
                ->where('user_id',auth()->id())
                ->whereNull('published_at')
                ->latest()
                ->paginate(5);       
        return view('admin.blogs.draft',compact(['blogs']));
    }

    public function restoreBlog(Blog $blog){
        $blog->published_at = now();
        $blog->save();

        session()->flash('success','Blog Restored!');
        return redirect(route('admin.blogs.index'));

    }

    public function drafted(Blog $blog){
        $blog->published_at = null;
        $blog->save();
        // ss($blog);
        session()->flash('success','Blog Drafted!');
        return redirect(route('admin.blogs.index'));
    }

    
    

}

resources/views/admin/blogs/draft.blade.php
@extends('admin.layout.app')

@section('main-content')
    <div class="container-fluid">
        <!--Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Drafts</h1>           
        </div>
        @include('admin.layout._alert-messages')
        <div class="row">
            <div class="col-md-12">
                <table class="table table-bordered">
                    <thead>
                        <th>ID</th>
                        <th>Image</th>
                        <th>Title</th>
                        <th>Excerpt</th>
                        <th>Category</th>
                        <th>Actions</th>
                    </thead>
                    <tbody>
                        @foreach ($blogs as $blog)
                            <tr>
                                <td>{{ $blog->id }}</td>
                                <td>
                                    <img src="{{ asset($blog->image_path) }}" alt="{{ $blog->title }}" width="80px">
                                </td>
                                <td>{{ $blog->title }}</td>
                                <td>{{ $blog->excerpt }}</td>
                                <td>{{ $blog->category->name }}</td>

                                <td>
                                    <button class="btn btn-primary" data-toggle="modal" data-target="#restoreModal"
                                        onclick="restoreModalHelper('{{ route('admin.blogs.restoreblog', $blog->id) }}')">
                                        <i class="fa fa-recycle"></i>
                                    </button>

                                    <button class="btn btn-danger" data-toggle="modal" data-target="#deleteModal"
                                        onclick="deleteModalHelper('{{ route('admin.blogs.trash', $blog->id) }}')">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                @if($blogs->count() == 0)
                    <p>No Blogs Found!</p>
                @endif
                {{ $blogs->links('vendor.pagination.bootstrap-5') }}
            </div>
        </div>
    </div>
    {{-- Delete Modal --}}
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <form action="" method="POST" id="deleteForm">
                @csrf
                @method('DELETE')
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Delete category?</h5>
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">Are you sure you want to delete the category?</div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                        <button class="btn btn-secondary" type="submit">Delete</button>
                    </div>
                </div>

            </form>
        </div>
    </div>
    {{-- Restore Modal --}}
    <div class="modal fade" id="restoreModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <form action="" method="POST" id="restoreForm">
                @csrf
                @method('POST')
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Restore Blog?</h5>
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">Do You want to restore the blog?</div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                        <button class="btn btn-secondary" type="submit">Restore</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        function deleteModalHelper(url) {
            console.log(url); 
            document.getElementById("deleteForm").setAttribute('action', url);
        }
        function restoreModalHelper(url) {
        console.log(url); 
        document.getElementById("restoreForm").setAttribute('action', url);
        }
    </script>
@endsection

resources/views/admin/blogs/index.blade.php
@extends('admin.layout.app')

@section('main-content')
    <div class="container-fluid">
        <!--Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Blog</h1>
            <a href={{ route('admin.blogs.create') }} class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                    class="fas fa-plus fa-sm text-white-50"></i> Create Blog</a>
        </div>
        @include('admin.layout._alert-messages')
        <div class="row">
            <div class="col-md-12">
                <table class="table table-bordered">
                    <thead>
                        <th>ID</th>
                        <th>Image</th>
                        <th>Title</th>
                        <th>Excerpt</th>
                        <th>Category</th>
                        <th>Actions</th>
                        <th>Draft Blog</th>
                    </thead>
                    <tbody>
                        @foreach ($blogs as $blog)
                            <tr>
                                <td>{{ $blog->id }}</td>
                                <td>
                                    <img src="{{ asset($blog->image_path) }}" alt="{{ $blog->title }}" width="80px">
                                </td>
                                <td>{{ $blog->title }}</td>
                                <td>{{ $blog->excerpt }}</td>
                                <td>{{ $blog->category->name }}</td>

                                <td>
                                    <a href="{{ route('admin.blogs.edit', $blog->id) }}" class="btn btn-primary">
                                        <i class="fas fa-pen"></i>
                                    </a>
                                    <button class="btn btn-danger" data-toggle="modal" data-target="#deleteModal"
                                        onclick="deleteModalHelper('{{ route('admin.blogs.trash', $blog->id) }}')">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                    
                                </td>
                                <td><button class="btn btn-secondary" data-toggle="modal" data-target="#draftModal"
                                        onclick="draftModalHelper('{{ route('admin.blogs.drafted', $blog->id) }}')">
                                        <i class="fa fa-archive"></i>
                                    </button></td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                @if($blogs->count() == 0)
                    <p>No Blogs Found!</p>
                @endif
                {{ $blogs->links('vendor.pagination.bootstrap-5') }}
            </div>
        </div>
    </div>
    {{-- Delete Modal --}}
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <form action="" method="POST" id="deleteForm">
                @csrf
                @method('DELETE')
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Delete category?</h5>
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">Are you sure you want to delete the category?</div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                        <button class="btn btn-secondary" type="submit">Delete</button>
                    </div>
                </div>

            </form>
        </div>
    </div>
    {{--Draft Modal --}}
    <div class="modal fade" id="draftModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <form action="" method="POST" id="draftForm">
                @csrf
                @method('POST')
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Delete category?</h5>
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">Are you sure you want to draft the blog?</div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                        <button class="btn btn-secondary" type="submit">Draft</button>
                    </div>
                </div>

            </form>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        function deleteModalHelper(url) {

            console.log(url); 
            document.getElementById("deleteForm").setAttribute('action', url);
        }
        function draftModalHelper(url) {
        console.log(url); 
        document.getElementById("draftForm").setAttribute('action', url);
}
    </script>
@endsection

resources/views/admin/blogs/trashed.blade.php
@extends('admin.layout.app')

@section('main-content')
    <div class="container-fluid">
        <!--Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Blog</h1>
            <a href={{ route('admin.blogs.create') }} class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                    class="fas fa-plus fa-sm text-white-50"></i> Create Blog</a>
        </div>
        @include('admin.layout._alert-messages')
        <div class="row">
            <div class="col-md-12">
                <table class="table table-bordered">
                    <thead>
                        <th>ID</th>
                        <th>Image</th>
                        <th>Title</th>
                        <th>Excerpt</th>
                        <th>Category</th>
                        <th>Actions</th>
                    </thead>
                    <tbody>
                        @foreach ($blogs as $blog)
                            <tr>
                                <td>{{ $blog->id }}</td>
                                <td>
                                    <img src="{{ asset($blog->image_path) }}" alt="{{ $blog->title }}" width="80px">
                                </td>
                                <td>{{ $blog->title }}</td>
                                <td>{{ $blog->excerpt }}</td>
                                <td>{{ $blog->category->name }}</td>

                                <td>
                                    < <button class="btn btn-danger" data-toggle="modal" data-target="#restoreModal"
                                        onclick="restoreModalHelper('{{ route('admin.blogs.restore', $blog->id) }}')">
                                        <i class="fa fa-recycle"></i>
                                    </button>


                                    <button class="btn btn-danger" data-toggle="modal" data-target="#deleteModal"
                                        onclick="deleteModalHelper('{{ route('admin.blogs.destroy', $blog->id) }}')">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                @if($blogs->count() == 0)
                    <p>No Blogs Found!</p>
                @endif
                {{ $blogs->links('vendor.pagination.bootstrap-5') }}
            </div>
        </div>
    </div>
    {{-- Delete Modal --}}
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <form action="" method="POST" id="deleteForm">
                @csrf
                @method('DELETE')
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Delete category?</h5>
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">Are you sure you want to delete the category?</div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                        <button class="btn btn-secondary" type="submit">Delete</button>
                    </div>
                </div>

            </form>
        </div>
    </div>
    <!-- End of delete Modal -->
    <!-- RESTORE Modal -->
    <div class="modal fade" id="restoreModal" tabindex="-1" role="dialog" aria-labelledby="restoreModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <form action="" method="POST" id="restoreForm">
                @csrf
                @method('PUT')
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Restore Blog?</h5>
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">Are you sure you want to restore the blog?</div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                        <button class="btn btn-secondary" type="submit">Restore</button>
                    </div>
                </div>

            </form>
        </div>
    </div>
@endsection


@section('scripts')
    <script>
        function deleteModalHelper(url) {

            console.log(url); //   http://localhost:8000/admin/categories/2
            document.getElementById("deleteForm").setAttribute('action', url);
        }
        function restoreModalHelper(url) {

            console.log(url); //   http://localhost:8000/admin/categories/2
            document.getElementById("restoreForm").setAttribute('action', url);
        }
    </script>
@endsection