routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\BlogsController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\CommentsController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::get('/',[FrontendController::class,'index'])->name('home');
Route::get('/categories/{category}/blogs',[FrontendController::class,'category'])->name('frontend.category');
Route::get('/tags/{tag}/blogs',[FrontendController::class,'tag'])->name('frontend.tag');
Route::get('/blogs/{blog}',[FrontendController::class,'show'])->name('frontend.blogs.show');
Route::post('/blogs/{blog}/comment',[FrontendController::class,'comment'])->name('frontend.blogs.comment');
Route::delete('/comments/{comment}/delete',[FrontendController::class,'delete'])->name('frontend.comments.delete');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {

    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    Route::prefix('/admin')->name('admin.')->group(function () {
        Route::get('/dashboard', function () {
            return view('admin.dashboard');
        })->name('dashboard');

        Route::get('/blogs/trashed',[BlogsController::class,'trashed'])->name('blogs.trashed');
        Route::get('/blogs/verify',[BlogsController::class,'verify'])->name('blogs.verifyblogs');
        Route::delete('/blogs/{blog}/trash',[BlogsController::class,'trash'])->name('blogs.trash');
        Route::put('/blogs/{blog}/restore',[BlogsController::class,'restore'])->name('blogs.restore');
        Route::post('/blogs/{blog}/verify',[BlogsController::class,'verifyBlog'])->name('blogs.verify');
        Route::post('/blogs/{blog}/unverify',[BlogsController::class,'unverifyBlog'])->name('blogs.unverify');

        Route::get('/blogs/draft',[BlogsController::class,'draft'])->name('blogs.draft');
        Route::post('/blogs/{blog}/restore',[BlogsController::class,'restoreBlog'])->name('blogs.restoreblog');
        Route::post('/blogs/{blog}/drafted',[BlogsController::class,'drafted'])->name('blogs.drafted');
        
        Route::post('/users/{user}/verify',[UsersController::class,'verify'])->name('users.verify');
        Route::post('/users/{user}/unverify',[UsersController::class,'unverify'])->name('users.unverify');
        Route::post('/users/{user}/makeAdmin',[UsersController::class,'makeAdmin'])->name('users.makeAdmin');
        Route::post('/users/{user}/makeAuthor',[UsersController::class,'makeAuthor'])->name('users.makeAuthor');
        
        Route::post('/comments/{comment}/verify',[CommentsController::class,'verify'])->name('comments.verify');
        

        Route::resource('categories', CategoriesController::class)->except(['show']);
        Route::resource('tags', TagsController::class);
        Route::resource('blogs', BlogsController::class);
        Route::resource('users',UsersController::class);  
        Route::resource('comments',CommentsController::class);      
    });
});

require __DIR__.'/auth.php';

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    public function blogs()
    {
        return $this->hasMany(Blog::class);
    }

    public function isAdmin(): bool{
        return $this->role === "admin";
    }

    public function isOwner(Blog $blog): bool{
        return $this->id === $blog->user_id;
    }

    public function isVerified(): bool{
        return  $this->email_verified_at != null;
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Requests\ProfileUpdateRequest;

class UsersController extends Controller
{
    public function index(){
        $users = User::paginate(5);
        return view('admin.Users.user',compact(['users']));
    }

    public function verify(User $user){
        // dd("hello im verified");
        // $email_verified_at = [now()];
        // // dd($email_verified_at);
        // $user->update($email_verified_at)
        //       ->where('user_id',$user->id);
        
        $user->email_verified_at = now();
        $user->save();
        session()->flash('success','Email Verified successfully...');
        return redirect(route('admin.users.index'));
        // dd($user);

    }
    public function unverify(User $user){
        $user->email_verified_at = NULL;
        if($user->role == 'admin'){
            $user->role = 'author';
        }
        $user->save();
        session()->flash('success','Email Unverified successfully...');
        return redirect(route('admin.users.index'));
        // dd("hello i am unverified");
    }

    public function makeAdmin(User $user){
        if($user->email_verified_at){
            $user->role="admin";
            $user->save();
            session()->flash('success','Congrats! You are an admin now.');
            // dd("Yay you are eleigible");
        }else{
            session()->flash('error','Cannot be switched to Admin. Please verify email first!');
        }
        
        return redirect(route('admin.users.index'));
    }

    public function makeAuthor(User $user){
        $user->role="author";
        $user->save();
        session()->flash('success','Role Switched to Author only...');
        return redirect(route('admin.users.index'));
    }
}

resources/views/admin/Users/user.blade.php
@extends('admin.layout.app')

@section('main-content')
    <div class="container-fluid">
        <!--Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
            
        </div>
        @include('admin.layout._alert-messages')
        @method('POST')
        <div class="row">
            <div class="col-md-12">
                <table class="table table-bordered">
                    <thead>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Email verified</th>
                        <th>Role</th>
                    </thead>
                    <tbody>
                        @foreach ($users as $user)
                            <tr>
                                <td>{{ $user->id }}</td>
                                <td>{{ $user->name }}</td>
                                <td>{{$user->email}}</td>
                                <td>
                                    @method('POST')
                                    @if($user->email_verified_at)
                                        <button class="btn btn-primary" data-toggle="modal"              data-target="#unverifyModal"
                                                    onclick="unverifyModalHelper('{{ route('admin.users.unverify', $user->id) }}')"> Unverify Email
                                                    
                                        </button>
                                    @else
                                        <button class="btn btn-primary" data-toggle="modal"               data-target="#verifyModal"
                                                onclick="verifyModalHelper('{{ route('admin.users.verify', $user->id) }}')"> Verify Email
                                                
                                        </button>
                                        
                                    @endif
                                </td>
                                <td>{{$user->role}}</td>
                                <td>
                                    
                                    @if($user->role =='author')
                                        <button class="btn btn-primary" data-toggle="modal"               data-target="#adminModal"
                                                    onclick="adminModalHelper('{{ route('admin.users.makeAdmin', $user->id) }}')"> Make as Admin    
                                        </button>
                                    @else
                                    <button class="btn btn-primary" data-toggle="modal"               data-target="#authorModal"
                                                    onclick="authorModalHelper('{{ route('admin.users.makeAuthor', $user->id) }}')"> Make as Author   
                                    </button>
                                    @endif
                                </td>
                                
                                <td>
                                    <a href="{{ route('admin.tags.edit', $user->id) }}" class="btn btn-primary">
                                        <i class="fas fa-pen"></i>
                                    </a>
                                    <button class="btn btn-danger" data-toggle="modal" data-target="#deleteModal"
                                        onclick="deleteModalHelper('{{ route('admin.tags.destroy', $user->id) }}')">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {{ $users->links('vendor.pagination.bootstrap-5') }}
            </div>
        </div>
    </div>
    {{-- Delete Modal --}}
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <form action="" method="POST" id="deleteForm">
                @csrf
                @method('DELETE')
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Delete category?</h5>
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">Are you sure you want to delete the category?</div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                        <button class="btn btn-secondary" type="submit">Delete</button>
                    </div>
                </div>

            </form>
        </div>
    </div>

    {{-- Verify Modal --}}
    <div class="modal fade" id="verifyModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <form action="" method="POST" id="verifyForm">
                @csrf
                @method('POST')
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Verify Email?</h5>
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">Are you sure you want to verify this user's email?</div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                        <button class="btn btn-secondary" type="submit">Verify</button>
                    </div>
                </div>

            </form>
        </div>
    </div>

    {{-- UnVerify Modal --}}
    <div class="modal fade" id="unverifyModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <form action="" method="POST" id="unverifyForm">
                @csrf
                @method('POST')
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Unverify Email?</h5>
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">Are you sure you want to unverify this user's email?</div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                        <button class="btn btn-secondary" type="submit">UnVerify</button>
                    </div>
                </div>

            </form>
        </div>
    </div>

    
    {{-- Admin Modal --}}
    <div class="modal fade" id="adminModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <form action="" method="POST" id="adminForm">
                @csrf
                @method('POST')
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Make Admin?</h5>
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">Are you sure you want to Switch the user role to Admin?</div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                        <button class="btn btn-secondary" type="submit">Switch</button>
                    </div>
                </div>

            </form>
        </div>
    </div>

    
    {{-- Author Modal --}}
    <div class="modal fade" id="authorModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <form action="" method="POST" id="authorForm">
                @csrf
                @method('POST')
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Make Author?</h5>
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">Do you want to switch the user role to Author?</div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                        <button class="btn btn-secondary" type="submit">Switch</button>
                    </div>
                </div>

            </form>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        function deleteModalHelper(url) {
            console.log(url);
            document.getElementById("deleteForm").setAttribute('action', url);
        }
        function verifyModalHelper(url) {
            console.log(url);
            document.getElementById("verifyForm").setAttribute('action', url);
        }
        function unverifyModalHelper(url) {
            console.log(url);
            document.getElementById("unverifyForm").setAttribute('action', url);
        }
        function adminModalHelper(url) {
            console.log(url);
            document.getElementById("adminForm").setAttribute('action', url);
        }
        function authorModalHelper(url) {
            console.log(url);
            document.getElementById("authorForm").setAttribute('action', url);
        }
    </script>
@endsection