routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\TagsController;
use App\Http\Controllers\BlogsController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\CommentsController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::get('/',[FrontendController::class,'index'])->name('home');
Route::get('/categories/{category}/blogs',[FrontendController::class,'category'])->name('frontend.category');
Route::get('/tags/{tag}/blogs',[FrontendController::class,'tag'])->name('frontend.tag');
Route::get('/blogs/{blog}',[FrontendController::class,'show'])->name('frontend.blogs.show');
Route::post('/blogs/{blog}/comment',[FrontendController::class,'comment'])->name('frontend.blogs.comment');
Route::delete('/comments/{comment}/delete',[FrontendController::class,'delete'])->name('frontend.comments.delete');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {

    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    Route::prefix('/admin')->name('admin.')->group(function () {
        Route::get('/dashboard', function () {
            return view('admin.dashboard');
        })->name('dashboard');

        Route::get('/blogs/trashed',[BlogsController::class,'trashed'])->name('blogs.trashed');
        Route::get('/blogs/verify',[BlogsController::class,'verify'])->name('blogs.verifyblogs');
        Route::delete('/blogs/{blog}/trash',[BlogsController::class,'trash'])->name('blogs.trash');
        Route::put('/blogs/{blog}/restore',[BlogsController::class,'restore'])->name('blogs.restore');
        Route::post('/blogs/{blog}/verify',[BlogsController::class,'verifyBlog'])->name('blogs.verify');
        Route::post('/blogs/{blog}/unverify',[BlogsController::class,'unverifyBlog'])->name('blogs.unverify');

        Route::get('/blogs/draft',[BlogsController::class,'draft'])->name('blogs.draft');
        Route::post('/blogs/{blog}/restore',[BlogsController::class,'restoreBlog'])->name('blogs.restoreblog');
        Route::post('/blogs/{blog}/drafted',[BlogsController::class,'drafted'])->name('blogs.drafted');
        
        Route::post('/users/{user}/verify',[UsersController::class,'verify'])->name('users.verify');
        Route::post('/users/{user}/unverify',[UsersController::class,'unverify'])->name('users.unverify');
        Route::post('/users/{user}/makeAdmin',[UsersController::class,'makeAdmin'])->name('users.makeAdmin');
        Route::post('/users/{user}/makeAuthor',[UsersController::class,'makeAuthor'])->name('users.makeAuthor');
        
        Route::post('/comments/{comment}/verify',[CommentsController::class,'verify'])->name('comments.verify');
        

        Route::resource('categories', CategoriesController::class)->except(['show']);
        Route::resource('tags', TagsController::class);
        Route::resource('blogs', BlogsController::class);
        Route::resource('users',UsersController::class);  
        Route::resource('comments',CommentsController::class);      
    });
});

require __DIR__.'/auth.php';

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;


class Category extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'created_by', 'last_updated_by'];
    //protected $guarded = [];


    public function blogs()
    {
        return $this->hasMany(Blog::class);
    }


}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Category;
use App\Http\Requests\Categories\CreateCategoryRequest;
use App\Http\Requests\Categories\UpdateCategoryRequest;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function __construct(){
        $this->middleware(['validateAdmin'])->only(['edit','update','destroy']);
    }
    public function index()
    {
        //
        // $categories = Category::paginate(2);
        $categories = Category::withCount('blogs')->latest('updated_at')->paginate(20);
        // $categories = Category::orderBy('id', 'asc')->paginate(2);
        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(CreateCategoryRequest $request)
    {
        //
        // dd($request->all());

        // $data=request()->all();
        // request()->validate([
        //     'name'=>'required|mi:3|max:255'
        // ]);

        $userId = auth()->user()->id;
        Category::create([
            'name' => $request->name,
            'created_by' => $userId,
            'last_updated_by' => $userId
        ]);

        // session()->put('success','Category created successfully...');
        session()->flash('success', 'Category create successfully...');
        return redirect(route('admin.categories.index'));

    }
    

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Category $category)
    {
        return view('admin.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateCategoryRequest $request, Category $category)
    {
        //
        $category->name = $request->name;
        $category->save();

        session()->flash('success', 'Category updated successfully...');
        return redirect(route('admin.categories.index'));

    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Request $request, Category $category)
    {
        //TODO:Validte whether the category has post associated with it.uf not then only proceed.

        if($category->blogs->count() > 0){
            session()->flash('error','Category cannot be deleted as it has posts associated');
            return redirect(route('admin.categories.index'));
        }
        $category->delete();
        session()->flash('success', 'Category deleted successfully...');
        return redirect(route('admin.categories.index'));

    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layout.app')

@section('main-content')
    <div class="container-fluid">
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
            <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                    class="fas fa-plus fa-sm text-white-50"></i> Create Category</a>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <form action="{{ route('admin.categories.store') }}" method="POST">
                            @csrf
                            <div class="form-group">
                                <label for="name" class="form-label">Name</label>
                                <input type="text" value="{{ old('name') }}"
                                    class="form-control @error('name') border-danger text-danger @enderror"
                                    placeholder="Enter Category Name" id="name" name="name">
                                @error('name')
                                    <span class="text-danger">
                                        {{-- {{$errors->has('name')?'ERROR':'No Error'}} --}}
                                        {{ $errors->first('name') }}
                                    </span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary" name="addCategory">Submit</button>
                            </div>
                        </form>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
    </div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layout.app')

@section('main-content')
    <div class="container-fluid">
        <!-- {{-- <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
            <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                    class="fas fa-plus fa-sm text-white-50"></i> Create Category</a>
        </div> --}} -->

        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <form action="{{ route('admin.categories.update', $category->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label for="name" class="form-label">Name</label>
                                <input type="text" value="{{ old('name', $category->name) }}"
                                    class="form-control @error('name') border-danger text-danger @enderror"
                                    placeholder="Enter Category Name" id="name" name="name">
                                @error('name')
                                    <span class="text-danger">
                                        {{-- {{$errors->has('name')?'ERROR':'No Error'}} --}}
                                        {{ $errors->first('name') }}
                                    </span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary" name="updateCategory">Submit</button>
                            </div>
                        </form>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
    </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layout.app')

@section('main-content')
    <div class="container-fluid">
        <!--Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
            <a href={{ route('admin.categories.create') }}
                class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                    class="fas fa-plus fa-sm text-white-50"></i> Create Category</a>
        </div>
        @include('admin.layout._alert-messages')
        <div class="row">
            <div class="col-md-12">
                <table class="table table-bordered">
                    <thead>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Post Count</th>
                        <th>Actions</th>
                    </thead>
                    <tbody>
                        @foreach ($categories as $category)
                            <tr>
                                <td>{{ $category->id }}</td>
                                <td>{{ $category->name }}</td>
                                <td>0</td>
                                <td>
                                    <a href="{{ route('admin.categories.edit', $category->id) }}" class="btn btn-primary">
                                        <i class="fas fa-pen"></i>
                                    </a>

                                    <button class="btn btn-danger" data-toggle="modal" data-target="#deleteModal"
                                        onclick="deleteModalHelper('{{ route('admin.categories.destroy', $category->id) }}')">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {{ $categories->links('vendor.pagination.bootstrap-5') }}
            </div>
        </div>
    </div>
    {{-- Delete Modal --}}
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <form action="" method="POST" id="deleteForm">
                @csrf
                @method('DELETE')
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Delete category?</h5>
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">Are you sure you want to delete the category?</div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                        <button class="btn btn-secondary" type="submit">Delete</button>
                    </div>
                </div>

            </form>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        function deleteModalHelper(url) {

            //console.log(url); //http://localhost:8000/admin/categories/2
            document.getElementById("deleteForm").setAttribute('action', url);
        }
    </script>
@endsection